language: ruby
dist: focal
cache:
- bundle
- yarn

rbenv:
- 2.6
- 2.7
- 3.0
- 3.1

node_js: lts/*

services:
- postgresql

before_deploy:
  - node -v
  - |
    npm i -g \
      semantic-release \
      @semantic-release/git \
      @semantic-release/changelog \
      semantic-release-rubygem

deploy:
  - provider: script
    script: ./release.sh
    on:
      branch: master
      condition: "$TRAVIS_RUBY_VERSION = 3.0"
before_install:
  - gem install rubygems-update -v 3.4.22
